version: 2
jobs:
  build:
    docker:
      - image: node:7.9.0

    working_directory: ~/share-button-study

    steps:
      - checkout

      - run:
          name: dependencies
          command: |
            apt-get update
            apt-get install zip

      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/ubuntu/.yarn-cache"

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Build .XPI
          command: npm run build

      - store_artifacts:
          path: "share-button-study.xpi"
