version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.10

    working_directory: ~/share-button-study

    steps:
      - checkout

      - run:
          name: dependencies
          command: |
            apt-get update -y
            apt-get install -y curl
            curl -sL https://deb.nodesource.com/setup_8.x | bash -
            apt-get install -y zip firefox xvfb nodejs

      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/ubuntu/.yarn-cache"

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Build .XPI
          command: npm run build

      - run:
          name: Functional tests
          command: npm run test

      - store_artifacts:
          path: "extension/share-button-study.xpi"
